cloudnet-web:
  image: jwilder/nginx-proxy:0.2.0
  restart: always
  volumes:
    - ./certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - cloudnet-app
  ports:
    - "80:80"
    - "443:443"

cloudnet-cron:
  image: onapp/cloudnet
  env_file: .env.docker
  restart: always
  links:
    - cloudnet-redis
    - cloudnet-db
    - cloudnet-memcached
  volumes:
    - ./log:/app/log
  command: foreman run cron

cloudnet-app:
  image: onapp/cloudnet
  env_file: .env.docker
  restart: always
  ports:
    - "9292"
  links:
    - cloudnet-redis
    - cloudnet-db
    - cloudnet-memcached
  volumes:
    - ./log:/app/log
  command: foreman run web

cloudnet-worker:
  image: onapp/cloudnet
  env_file: .env.docker
  restart: always
  links:
    - cloudnet-redis
    - cloudnet-db
    - cloudnet-memcached
  volumes:
    - ./log:/app/log
  command: foreman run sidekiq --logfile /app/log/sidekiq.log

cloudnet-redis:
  image: redis
  restart: always

cloudnet-memcached:
  image: memcached
  restart: always

cloudnet-dbdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: "true"

cloudnet-db:
  image: postgres
  ports:
    - "5432"
  volumes_from:
    - cloudnet-dbdata
  restart: always

cloudnet-dbbackup:
  image: hackedunit/docker-postgres-backup
  env_file: .env.docker
  restart: always
  links:
    - cloudnet-db
